[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-cython", "Cython>=3.1", "setuptools", "numpy>=2.0"]
build-backend = "hatchling.build"

[project]
name = "pyresample"
dynamic = ["version"]
description = "Geospatial image resampling in Python"
readme = "README.md"
license = "LGPL-3.0-or-later"
license-files = ["LICENSE.txt"]
authors = [
  { name = "Thomas Lavergne", email = "t.lavergne@met.no" },
]
requires-python = ">=3.12"
dependencies = [
  "pyproj>=3.0",
  "configobj",
  "pykdtree>=1.3.1",
  "pyyaml",
  "numpy>=1.25.0",
  "shapely",
  "donfig",
  "platformdirs",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python",
  "Programming Language :: Cython",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python :: Free Threading :: 1 - Unstable",
]

[project.urls]
Homepage = "https://github.com/pytroll/pyresample"

[project.optional-dependencies]
numexpr = ["numexpr"]
quicklook = ["matplotlib", "cartopy>=0.20.0", "pillow"]
rasterio = ["rasterio"]
dask = ["dask>=0.16.1"]
cf = ["xarray"]
gradient_search = ["shapely"]
xarray_bilinear = ["xarray", "dask", "zarr"]
odc-geo = ["odc-geo"]
tests = [
  "rasterio",
  "dask",
  "xarray",
  "cartopy>=0.20.0",
  "pillow",
  "matplotlib",
  "scipy",
  "zarr",
  "pytest-lazy-fixtures",
  "shapely",
  "odc-geo",
]
all = [
  "pyresample[numexpr,quicklook,rasterio,dask,cf,gradient_search,xarray_bilinear,odc-geo,tests]",
]

[project.entry-points."pyresample.resamplers"]
nearest = "pyresample.future.resamplers.nearest:KDTreeNearestXarrayResampler"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.sdist]
include = [
  "pyresample/",
  "docs/",
  "LICENSE.txt",
  "README.md",
  "CHANGELOG.md",
]


[tool.hatch.build.targets.wheel]
packages = ["pyresample"]

# Required by hatch-cython's internal use of setuptools build_ext
[tool.setuptools]
packages = ["pyresample"]

[tool.hatch.build.targets.wheel.hooks.cython]
dependencies = ["hatch-cython"]

[tool.hatch.build.targets.wheel.hooks.cython.options]
include_numpy = true
compile_py = false
directives = { language_level = 3, freethreading_compatible = true }
define_macros = [["NPY_NO_DEPRECATED_API", "NPY_1_25_API_VERSION"]]
compile_args = [
  { platforms = ["linux", "darwin", "freebsd"], arg = "-O3" },
  { platforms = ["linux", "darwin", "freebsd"], arg = "-Wno-unused-function" },
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
# See https://docs.astral.sh/ruff/rules/
select = ["E", "W", "B", "D", "T10", "C90", "NPY"]
# Remove D416 when all docstrings have been converted to google-style
ignore = ["D107", "D416"]

[tool.ruff.lint.per-file-ignores]
"pyresample/test/*.py" = ["D102", "D103", "S101"]  # assert allowed in tests

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.mypy]
python_version = "3.12"
# See https://github.com/python/mypy/issues/12286 for automatic multi-platform support
platform = "linux"
# platform = win32
# platform = darwin
allow_untyped_decorators = false
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
warn_unused_configs = true

[tool.isort]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
profile = "black"
skip_gitignore = true
default_section = "THIRDPARTY"
known_first_party = "pyresample"
line_length = 120

[tool.coverage.run]
relative_files = true

[tool.uv.workspace]
members = [
    ".",
]
